# Generated by Django 3.1.4 on 2020-12-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.BooleanField(default=False),
        ),
    ]
